tap "amazon/amazon", "ssh://git.amazon.com/pkg/HomebrewAmazon"
tap "cmacrae/formulae"
tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "python@3.9"
brew "dbus"
brew "fzf"
brew "gcc"
brew "git"
brew "ifstat"
brew "jq"
brew "lua"
brew "mas"
brew "neofetch"
brew "neovim"
brew "node"
brew "ruby"
brew "shellcheck"
brew "terminal-notifier"
brew "wakeonlan"
brew "yarn"
brew "amazon/amazon/ninja-dev-sync"
brew "cmacrae/formulae/spacebar"
brew "felixkratz/formulae/sketchybar"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "agenda"
cask "android-platform-tools"
cask "appcleaner"
cask "authy"
cask "cyberduck"
cask "datagrip"
cask "dcv-viewer"
cask "fbreader"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "hammerspoon"
cask "hiddenbar"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "kodi"
cask "logitech-g-hub"
cask "maccy"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-edge-dev"
cask "monitorcontrol"
cask "mos"
cask "motrix"
cask "postman"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "table-tool"
cask "unnaturalscrollwheels"
cask "visual-studio-code"
cask "wiznote"
mas "AudioBookBinder", id: 413969927
mas "Bitwarden", id: 1352778147
mas "Fresco", id: 1251572132
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Swol", id: 1502303446
