#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_border_blur           off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# window configs
#yabai -m config window_border                on
#yabai -m config window_border_width          3
#yabai -m config window_border_radius         10
#yabai -m config active_window_border_color   0xFF00BFFF
#yabai -m config normal_window_border_color   0x00FFFFFF
#yabai -m config focus_follows_mouse          autoraise

# ===== Rules ==================================

yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" layer=above manage=off
yabai -m rule --add label="System Information" app="^System Information$" title=".*" layer=above manage=off
yabai -m rule --add label="Iterm2" app="^iTerm2$" manage=off
yabai -m rule --add app="Cisco AnyConnect Secure Mobility Client" manage=off
yabai -m rule --add app="Irvue" manage=off
yabai -m rule --add app="Books" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="Fresco" manage=off
yabai -m rule --add app="Unite" manage=off
yabai -m rule --add app="Kodi" manage=off
yabai -m rule --add app="Coherence X" manage=off
yabai -m rule --add app="Authy Desktop" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Microsoft Outlook" title="Outlook Preferences" manage=off
yabai -m rule --add app="Mac Mouse Fix" manage=off
yabai -m rule --add app="ACME" manage=off
yabai -m rule --add app="Terminal" manage=off
yabai -m rule --add app="Stickies" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="^Browserosaurus$" manage=off
yabai -m rule --add app="Ente Auth" title="Ente Auth" manage=off

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash /Users/tahmhd/.config/customScripts/windowFocusOnDestroy.sh"

# make sure apps are opened in correct display
yabai -m rule --add app="Spotify" display=^4 
yabai -m rule --add app="scrcpy" space=17

#yabai -m config external_bar all:45:0

#borders hidpi=off active_color=0xFF47CBFF inactive_color=0x00FFFFFF blur_radius=0.5 width=5.0 style=round 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
