#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_border                off

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight --config ~/.config/limelight/limelightrc &>/dev/null &

# ===== Rules ==================================

yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Iterm2" app="^iTerm2$" manage=off
yabai -m rule --add app="Cisco AnyConnect Secure Mobility Client" manage=off
yabai -m rule --add app="Irvue" manage=off
yabai -m rule --add app="Finder" title="Copy" manage=off
yabai -m rule --add app="Books" manage=off
yabai -m rule --add app="^iTerm2$" manage=off

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash /Users/tahmhd/.config/customScripts/windowFocusOnDestroy.sh"

echo "yabai configuration loaded.."
